# Generated by Django 4.2.3 on 2023-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://5.imimg.com/data5/OF/VM/MY-29875862/chocolate-cone-ice-cream.jpg', max_length=500),
        ),
    ]
