# Generated by Django 4.2.3 on 2023-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default="'https://starinfinitefood.com/wp-content/uploads/2017/01/photo-1446034730750-a0b64d06ad13.jpeg'", max_length=500),
        ),
    ]
