# Generated by Django 4.2.3 on 2023-09-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://img.freepik.com/free-photo/delicious-ice-cream-with-topping_23-2150735572.jpg?t=st=1693899682~exp=1693903282~hmac=7f7e15d858acadab0a506b6263713eb3e30e33c654ee9289c59820ca55e495c6&w=740', max_length=500)),
            ],
        ),
    ]
