# Generated by Django 4.2.3 on 2023-09-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0005_item1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item1',
            old_name='item_desc',
            new_name='item1_desc',
        ),
        migrations.RenameField(
            model_name='item1',
            old_name='item_image',
            new_name='item1_image',
        ),
        migrations.RenameField(
            model_name='item1',
            old_name='item_name',
            new_name='item1_name',
        ),
        migrations.RenameField(
            model_name='item1',
            old_name='item_price',
            new_name='item1_price',
        ),
    ]
