# Generated by Django 4.2.3 on 2023-10-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0006_rename_item_desc_item1_item1_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('op_type', models.CharField(max_length=100)),
            ],
        ),
    ]
