# Generated by Django 4.2.3 on 2023-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0008_history_prod_ref_item_prod_code_item1_prod_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item1',
            name='prod_code',
        ),
        migrations.AddField(
            model_name='item1',
            name='prod1_code',
            field=models.IntegerField(default=200),
        ),
    ]
