# Generated by Django 4.2.3 on 2023-10-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0009_remove_item1_prod_code_item1_prod1_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item1',
            name='prod1_code',
        ),
    ]
