# Generated by Django 4.2.3 on 2023-10-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0012_alter_item1_prod1_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item1',
            name='prod1_code',
            field=models.IntegerField(default=300),
        ),
    ]
