# Generated by Django 4.2.3 on 2023-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0013_alter_item1_prod1_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='prod_ref',
            field=models.IntegerField(default=500),
        ),
    ]
