# Generated by Django 4.2.3 on 2023-10-05 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0016_item1_prod1_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
