# Generated by Django 4.2.3 on 2023-10-11 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0019_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 12, 13, 30, 52790)),
        ),
    ]
