# Generated by Django 4.2.3 on 2023-10-25 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0023_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 0, 32, 39, 508277)),
        ),
    ]
