# Generated by Django 4.2.3 on 2023-10-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icecreame', '0022_wishlist_alter_contact_date_wishlistitem1_and_more'),
        ('Icecreame', '0025_wishlist_alter_contact_date_order1_order'),
    ]

    operations = [
    ]
